### ISSUE TITLE
Add Global header navigation modules

### ISSUE THREAD

**Issue by mohanb-cms** [CMSgov/HealthCare.gov-Styleguide#165]
Add Global header navigation modules on /design/global/ section. The global navigation module shouldn't highlights any of the ind/family or Small business tabs.

**Comment by mliupaeter** [comment]
Maybe that page needs to be organized differently? Starting off with "global" as the "tophat" header and divide into audience section, ind&fam and SHOP. I've created a jira ticket: https://jira.cms.gov/browse/WDSG-177

**Comment by mliupaeter** [comment]
Top hat was added into the http://styleguide.healthcare.gov/design/global page.
