### ISSUE TITLE
Add "Google Tag Manager" for Github pages

### ISSUE THREAD

**Issue by nmudd-cms** [CMSgov/HealthCare.gov-Styleguide#54]
We'll work with Blast to add GA, Chartbeat, etc...

@averysmithproductions

**Comment by mliupaeter** [comment]
@rmungara - Is this issue good to close?

**Comment by rmungara** [comment]
@mliupaeter - Yes this is complete.

**Comment by mliupaeter** [comment]
@rmungara - Thanks!
