### ISSUE TITLE
add a contriubtion.md file

### ISSUE THREAD

**Issue by nmudd-cms** [CMSgov/HealthCare.gov-Styleguide#57]
https://github.com/government/best-practices/blob/master/CONTRIBUTING.md

**Comment by mliupaeter** [comment]
@nmudd-cms link doesn't work anymore.

**Comment by mliupaeter** [comment]
Contributing file added here: https://github.com/CMSgov/HealthCare.gov-Styleguide/blob/master/CONTRIBUTING.md
